import { useState } from 'react';
import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import { useQuery } from 'react-query';

// apis
import { fetchGithubProfile } from './api/apis';
import axios from 'axios';

// interfaces
interface Username {
  name: string;
}

// components
import ResultSection from '../components/ResultSection';

const Home: NextPage = () => {
  const [isLoading, setIsLoading] = useState(true);
  const [username, setUsername] = useState<Username>();
  const [profile, setProfile] = useState([]);
  const [repos, setRepos] = useState([]);

  const handleInputUsername = async (event: any) => {
    setUsername(event.target.value);
  };

  const fetchProfile = async () => {
    if (!username) {
      alert('Please input a username first!');
      return;
    }

    setIsLoading(true);
    try {
      const res = await axios.get(`https://api.github.com/users/${username}`);

      setProfile(res.data);

      try {
        const resRepos = await axios.get(res.data.repos_url);

        setRepos(resRepos.data);
      } catch (error) {
        console.log(error);
      }
    } catch (error) {
      console.log(error);
    }
    setIsLoading(false);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>GitHub Profile Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo.svg" height="44" width="41" alt="logo" />
        <h1 className={styles.main__title}>GitHub Profile Finder</h1>

        <div className={styles.main__search_container}>
          <input
            className={styles.main__search_bar}
            type="text"
            placeholder="Enter a username..."
            onChange={handleInputUsername}
          />
          <button className={styles.main__search_button} onClick={fetchProfile}>
            Search
          </button>
        </div>

        {!isLoading && <ResultSection data={profile} repos={repos} />}
      </main>
    </div>
  );
};

export default Home;
