import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Image src="/logo.svg" height="44" width="41" alt="logo" />
        <h1 className={styles.main__title}>GitHub Profile Finder</h1>

        <div className={styles.main__search_container}>
          <input className={styles.main__search_bar} type="text" placeholder="Enter a username..." />
          <button className={styles.main__search_button}>Search</button>
        </div>
      </main>
    </div>
  );
};

export default Home;
